version: '2'

networks:
  metfamily_net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.38.38.0/24
        ip_range: 10.38.38.0/24
        gateway: 10.38.38.1

services:
  metfamily:
    image: korseby/metfamily
    networks:
    - metfamily_net
    volumes:
    - /vol/R/shiny/srv/shiny-server/MetFam:/vol/R/shiny/srv/shiny-server/MetFam
    expose:
    - 3838
    restart: always

  haproxy:
    container_name: metfamily_haproxy
    build: metfamily-haproxy
    networks:
    - metfamily_net
    volumes:
    - ./metfamily-haproxy:/haproxy-override
    links:
    - metfamily
    ports:
    - "9001:80"
    - "9002:70"
    expose:
    - "80"
    - "70"
    restart: always

